# desafiopoo-umliphone
## Desafio UML iPhone

@startuml



class iPhone
class ReprodutorMusical
class AparelhoTelefonico
class NavegadorInternet

iPhone --> ReprodutorMusical
iPhone --> AparelhoTelefonico
iPhone --> NavegadorInternet

class iPhone {
}

class ReprodutorMusical{
+"+"tocar()
+"+"pausar()
+"+"selecionarMusica(String musica)
}

class AparelhoTelefonico{
+"+"ligar(String numero)
+"+"atender()
+"+"iniciarCorreioVoz()
}

class NavegadorInternet{
+"+"exibirPagina(String url)
+"+"adicionarNovaAba()
+"+" atualizarPagina()
}

(https://github.com/daniloterashima/desafiopoo-umliphone/blob/main/Captura%20de%20tela%202024-06-14%20001735.png)






@enduml
